name: Move Files
on: workflow_dispatch
jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Move files
        run: |
          shopt -s dotglob
          cp -rn FileExplorer/* .
          rm -rf FileExplorer
      - name: Commit and push
        run: |
          git config --global user.name "Zapia AI"
          git config --global user.email "zapia@brainlogic.ai"
          git add .
          git commit -m "Move files from FileExplorer to root" || echo "No changes"
          git push
